/**
 * Reference config after demo Beat 3 (and again after restoring the red/green demo).
 * Keep generator headers in your app; compare config() rather than file bytes.
 */
component extends="Model" {
	function config() {
		// Generated by: scaffold Post 'title:string{50}' body:text publishedAt:datetime
		validatesPresenceOf("title,body,publishedAt");
		validatesLengthOf(property="title", maximum=50, allowBlank=true);

		// The two deliberate Beat 3 additions.
		validatesExclusionOf(property="title", list="Untitled");
		hasMany(name="comments");
	}
}
