<cfscript>
	/*
		Use this file to configure your application.
		You can also use the environment specific files (e.g. /config/production/settings.cfm) to override settings set here.
		Don't forget to issue a reload request (e.g. reload=true) after making changes.
		See https://guides.wheels.dev/v4-0-0/core-concepts/environments-and-configuration/ for more info.
	*/

	/*
		Set data source name. By default uses the app name.
		Uncomment username/password if your datasource requires them.
	*/
	set(dataSourceName="{{datasourceName}}");
	// set(dataSourceUserName="");
	// set(dataSourcePassword="");

	/*
		URL rewriting mode: "On", "Partial", or "Off".
		"On" requires web server rewrite rules (or urlrewrite.xml for LuCLI/Tuckey).
		"Partial" requires cgi.path_info support.
	*/
	set(URLRewriting="On");

	// Reload your application with ?reload=true&password=<your WHEELS_RELOAD_PASSWORD>
	// The secret is read from .env (git-ignored) so it never lands in version control.
	set(reloadPassword=env("WHEELS_RELOAD_PASSWORD", ""));

	/*
		Migrator: produce `<name>_id` columns from t.references() and friends
		(matching Wheels model `belongsTo` defaults). Default in the framework
		is `false` for backwards compatibility with existing apps; new apps
		generated by `wheels new` opt in here. Flip to false if you need the
		legacy `<name>id` (no underscore) suffix.
	*/
	set(useUnderscoreReferenceColumns=true);

	/*
		Stacked form layout (#3549) and in-field validation errors (#3550).
		labelPlacement="before" puts the label on its own line; wheels.css
		makes text inputs full width. includeFormErrorMessages nests the
		per-field error inside the control's error wrapper. Existing apps
		that already set(functionName=...) keep those options.
		Checkboxes/radios stay beside their labels (around placement).
	*/
	set(includeFormErrorMessages=true);
	set(
		functionName="textField,textArea,passwordField,select,fileField,emailField,urlField,numberField,telField,dateField,searchField,colorField,rangeField",
		labelPlacement="before"
	);

	// CLI-Appends-Here
</cfscript>
