<cfscript>
	/*
		Use this file to configure your application.
		You can also use the environment specific files (e.g. /config/production/settings.cfm) to override settings set here.
		Don't forget to issue a reload request (e.g. reload=true) after making changes.
		See https://guides.wheels.dev/v4-0-0/core-concepts/environments-and-configuration/ for more info.
	*/

	/*
		Set data source name. By default uses the app name.
		Uncomment username/password if your datasource requires them.
	*/
	set(dataSourceName="{{datasourceName}}");
	// set(dataSourceUserName="");
	// set(dataSourcePassword="");

	/*
		URL rewriting mode: "On", "Partial", or "Off".
		"On" requires web server rewrite rules (or urlrewrite.xml for LuCLI/Tuckey).
		"Partial" requires cgi.path_info support.
	*/
	set(URLRewriting="On");

	// Reload your application with ?reload=true&password=<your WHEELS_RELOAD_PASSWORD>
	// The secret is read from .env (git-ignored) so it never lands in version control.
	set(reloadPassword=env("WHEELS_RELOAD_PASSWORD", ""));

	/*
		Migrator: produce `<name>_id` columns from t.references() and friends
		(matching Wheels model `belongsTo` defaults). Default in the framework
		is `false` for backwards compatibility with existing apps; new apps
		generated by `wheels new` opt in here. Flip to false if you need the
		legacy `<name>id` (no underscore) suffix.
	*/
	set(useUnderscoreReferenceColumns=true);

	/*
		Form helper defaults for scaffolded forms (issues #3549 / #3550):
		stack the label above the field, let string/text inputs span the full
		row width (via public/stylesheets/wheels-forms.css), and nest each
		property's validation error inside the field block. These are defaults
		for NEW scaffolds only — the framework's global `labelPlacement` stays
		`around` so existing apps and exact-HTML expectations are unaffected.
	*/
	set(
		functionName="textField,textFieldTag,emailField,emailFieldTag,urlField,urlFieldTag,numberField,numberFieldTag,telField,telFieldTag,searchField,searchFieldTag,passwordField,passwordFieldTag,textArea,textAreaTag,select,selectTag,fileField,fileFieldTag",
		labelPlacement="before",
		prependToLabel="<div class=""field"">",
		append="</div>",
		errorElement="div",
		errorClass="field-with-errors",
		encode="attributes"
	);
	// Boolean controls stay inline (label beside the checkbox/radio).
	set(
		functionName="checkBox,checkBoxTag,radioButton,radioButtonTag",
		labelPlacement="aroundRight"
	);
	// Accessible validation errors: a "Error:" text prefix is a non-color cue
	// (red styling lives in wheels-forms.css).
	set(
		functionName="errorMessageOn",
		prependText="Error:",
		wrapperElement="span",
		class="error-message"
	);
	set(
		functionName="errorMessagesFor",
		class="error-messages"
	);

	// CLI-Appends-Here
</cfscript>
